# Generated by Django 6.0.7 on 2026-07-27 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('website_name', models.CharField(max_length=150)),
                ('business_name', models.CharField(max_length=150)),
                ('business_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('STARTUP', 'Startup'), ('SMALL_BUSINESS', 'Small business'), ('ENTERPRISE', 'Enterprise'), ('NON_PROFIT', 'Non-profit'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('preferred_delivery_date', models.DateField(blank=True, null=True)),
                ('reference_links', models.JSONField(blank=True, default=list)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.package')),
                ('website_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.websitecategory')),
                ('website_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.websitetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='bookings.booking')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requirements', to='bookings.booking')),
                ('website_feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_requirements', to='catalog.websitefeature')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='required_features',
            field=models.ManyToManyField(related_name='bookings', through='bookings.BookingRequirement', to='catalog.websitefeature'),
        ),
        migrations.CreateModel(
            name='CustomerRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_requirements', to='bookings.booking')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeveloperAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_note', models.CharField(blank=True, default='', max_length=100)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_assignments', to='bookings.booking')),
                ('developer', models.ForeignKey(limit_choices_to={'role': 'DEVELOPER'}, on_delete=django.db.models.deletion.PROTECT, related_name='developer_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('storage_provider', models.CharField(max_length=20)),
                ('storage_key', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_category', models.CharField(choices=[('IMAGE', 'Image'), ('PDF', 'PDF'), ('ZIP', 'ZIP archive'), ('DOCX', 'Word document'), ('SPREADSHEET', 'Spreadsheet'), ('TEXT', 'Text file')], max_length=20)),
                ('file_size', models.PositiveBigIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bookings.booking')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_terminal', models.BooleanField(default=False, help_text='No further transitions expected once a booking reaches this status.')),
                ('is_default', models.BooleanField(default=False, help_text='Status assigned to a brand-new booking.')),
                ('color', models.CharField(blank=True, default='', help_text='Badge color hint for the UI.', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'project statuses',
                'ordering': ['sort_order'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_status')],
            },
        ),
        migrations.CreateModel(
            name='BookingTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BOOKING_CREATED', 'Booking created'), ('STATUS_CHANGED', 'Status changed'), ('NOTE_ADDED', 'Note added'), ('FILE_UPLOADED', 'File uploaded'), ('FILE_DELETED', 'File deleted'), ('DEVELOPER_ASSIGNED', 'Developer assigned'), ('DEVELOPER_UNASSIGNED', 'Developer unassigned'), ('BOOKING_CANCELLED', 'Booking cancelled')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_timeline_events', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='bookings.booking')),
                ('from_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bookings.projectstatus')),
                ('to_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bookings.projectstatus')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.projectstatus'),
        ),
        migrations.AddConstraint(
            model_name='bookingrequirement',
            constraint=models.UniqueConstraint(fields=('booking', 'website_feature'), name='unique_feature_per_booking'),
        ),
        migrations.AddConstraint(
            model_name='developerassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('booking', 'developer'), name='unique_active_assignment_per_developer'),
        ),
        migrations.AddIndex(
            model_name='projectattachment',
            index=models.Index(fields=['booking', '-created_at'], name='bookings_pr_booking_1bc789_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingtimeline',
            index=models.Index(fields=['booking', '-created_at'], name='bookings_bo_booking_6c2913_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'status'], name='bookings_bo_custome_2bb824_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', '-created_at'], name='bookings_bo_status__54a0d9_idx'),
        ),
    ]