# Generated by Django 6.0.7 on 2026-08-27 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_seed_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BOOKING_ACCEPTED', 'Booking accepted'), ('BOOKING_REJECTED', 'Booking rejected'), ('DEVELOPER_ASSIGNED', 'Developer assigned'), ('PROJECT_STARTED', 'Project started'), ('REVISION_REQUESTED', 'Revision requested'), ('DELIVERY_SUBMITTED', 'Delivery submitted'), ('PROJECT_COMPLETED', 'Project completed'), ('PROJECT_CANCELLED', 'Project cancelled')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('final_url', models.URLField(blank=True, default='')),
                ('access_instructions', models.TextField(blank=True, default='')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('REQUIREMENTS', 'Requirements'), ('PLANNING', 'Planning'), ('DESIGN', 'Design'), ('DEVELOPMENT', 'Development'), ('TESTING', 'Testing'), ('DELIVERY', 'Delivery')], max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RevisionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACKNOWLEDGED', 'Acknowledged'), ('LIMIT_EXCEEDED', 'Exceeds included revisions')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='bookingtimeline',
            name='event_type',
            field=models.CharField(choices=[('BOOKING_CREATED', 'Booking created'), ('STATUS_CHANGED', 'Status changed'), ('NOTE_ADDED', 'Note added'), ('FILE_UPLOADED', 'File uploaded'), ('FILE_DELETED', 'File deleted'), ('DEVELOPER_ASSIGNED', 'Developer assigned'), ('DEVELOPER_UNASSIGNED', 'Developer unassigned'), ('BOOKING_CANCELLED', 'Booking cancelled'), ('PROJECT_ACCEPTED', 'Project accepted'), ('PROJECT_REJECTED', 'Project rejected'), ('PROJECT_STARTED', 'Project started'), ('MILESTONE_COMPLETED', 'Milestone completed'), ('REVISION_REQUESTED', 'Revision requested'), ('DELIVERY_SUBMITTED', 'Delivery submitted'), ('DELIVERY_ACCEPTED', 'Delivery accepted'), ('PROJECT_COMPLETED', 'Project completed')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='developerassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('booking',), name='unique_active_assignment_per_booking'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdelivery',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='projectdelivery',
            name='delivered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdelivery',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='deliveries', to='bookings.projectattachment'),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bookings.projectattachment'),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['recipient', '-created_at'], name='bookings_no_recipie_a97455_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['recipient', 'is_read'], name='bookings_no_recipie_301a95_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectmilestone',
            constraint=models.UniqueConstraint(fields=('booking', 'stage'), name='unique_stage_per_booking'),
        ),
        migrations.AddIndex(
            model_name='revisionrequest',
            index=models.Index(fields=['booking', '-created_at'], name='bookings_re_booking_0cc72c_idx'),
        ),
    ]