# Generated by Django 6.0.7 on 2026-08-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_seed_lifecycle_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtimeline',
            name='event_type',
            field=models.CharField(choices=[('BOOKING_CREATED', 'Booking created'), ('STATUS_CHANGED', 'Status changed'), ('NOTE_ADDED', 'Note added'), ('FILE_UPLOADED', 'File uploaded'), ('FILE_DELETED', 'File deleted'), ('DEVELOPER_ASSIGNED', 'Developer assigned'), ('DEVELOPER_UNASSIGNED', 'Developer unassigned'), ('BOOKING_CANCELLED', 'Booking cancelled'), ('PROJECT_ACCEPTED', 'Project accepted'), ('PROJECT_REJECTED', 'Project rejected'), ('PROJECT_STARTED', 'Project started'), ('MILESTONE_COMPLETED', 'Milestone completed'), ('REVISION_REQUESTED', 'Revision requested'), ('DELIVERY_SUBMITTED', 'Delivery submitted'), ('DELIVERY_ACCEPTED', 'Delivery accepted'), ('PROJECT_COMPLETED', 'Project completed'), ('REQUIREMENTS_UPDATED', 'Requirements updated')], max_length=30),
        ),
    ]