# Generated by Django 6.0.7 on 2026-08-11 18:05

import apps.configuration.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password', apps.configuration.fields.EncryptedTextField(blank=True, default='')),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254)),
                ('reply_email', models.EmailField(blank=True, default='', max_length=254)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_success', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
            },
        ),
        migrations.CreateModel(
            name='FeatureFlags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_enabled', models.BooleanField(default=True)),
                ('booking_enabled', models.BooleanField(default=True)),
                ('reviews_enabled', models.BooleanField(default=True)),
                ('support_enabled', models.BooleanField(default=True)),
                ('payments_enabled', models.BooleanField(default=False)),
                ('registration_enabled', models.BooleanField(default=True)),
                ('developer_signup_enabled', models.BooleanField(default=True)),
                ('customer_signup_enabled', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Feature Flags',
                'verbose_name_plural': 'Feature Flags',
            },
        ),
        migrations.CreateModel(
            name='PaymentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razorpay_key_id', models.CharField(blank=True, default='', max_length=255)),
                ('razorpay_key_secret', apps.configuration.fields.EncryptedTextField(blank=True, default='')),
                ('razorpay_webhook_secret', apps.configuration.fields.EncryptedTextField(blank=True, default='')),
                ('default_currency', models.CharField(default='INR', max_length=3)),
                ('mode', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('LIVE', 'Live')], default='SANDBOX', max_length=10)),
                ('is_enabled', models.BooleanField(default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_success', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment Configuration',
            },
        ),
        migrations.CreateModel(
            name='SEOConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.CharField(blank=True, default='', max_length=500)),
                ('meta_keywords', models.CharField(blank=True, default='', max_length=500)),
                ('canonical_url', models.URLField(blank=True, default='')),
                ('robots_directive', models.CharField(default='index, follow', max_length=100)),
                ('google_verification', models.CharField(blank=True, default='', max_length=255)),
                ('bing_verification', models.CharField(blank=True, default='', max_length=255)),
                ('og_title', models.CharField(blank=True, default='', max_length=255)),
                ('og_description', models.CharField(blank=True, default='', max_length=500)),
                ('facebook_domain_verification', models.CharField(blank=True, default='', max_length=255)),
                ('twitter_site', models.CharField(blank=True, default='', max_length=100)),
                ('twitter_card_type', models.CharField(default='summary_large_image', max_length=30)),
                ('default_share_image_url', models.CharField(blank=True, default='', max_length=500)),
                ('default_share_image_key', models.CharField(blank=True, default='', max_length=500)),
                ('json_ld_schema', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'SEO Configuration',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website_name', models.CharField(default='CraftLaunch', max_length=100)),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('logo_key', models.CharField(blank=True, default='', max_length=500)),
                ('favicon_url', models.CharField(blank=True, default='', max_length=500)),
                ('favicon_key', models.CharField(blank=True, default='', max_length=500)),
                ('footer_logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('footer_logo_key', models.CharField(blank=True, default='', max_length=500)),
                ('light_logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('light_logo_key', models.CharField(blank=True, default='', max_length=500)),
                ('dark_logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('dark_logo_key', models.CharField(blank=True, default='', max_length=500)),
                ('primary_color', models.CharField(default='#D97706', max_length=7)),
                ('secondary_color', models.CharField(default='#78716C', max_length=7)),
                ('accent_color', models.CharField(default='#F59E0B', max_length=7)),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('support_phone', models.CharField(blank=True, default='', max_length=30)),
                ('business_address', models.TextField(blank=True, default='')),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('copyright_text', models.CharField(blank=True, default='', max_length=255)),
                ('footer_text', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='StorageConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_provider', models.CharField(choices=[('LOCAL', 'Local disk'), ('S3', 'Amazon S3'), ('CLOUDINARY', 'Cloudinary')], default='LOCAL', max_length=20)),
                ('s3_enabled', models.BooleanField(default=False)),
                ('cloudinary_enabled', models.BooleanField(default=False)),
                ('s3_access_key_id', models.CharField(blank=True, default='', max_length=255)),
                ('s3_secret_access_key', apps.configuration.fields.EncryptedTextField(blank=True, default='')),
                ('s3_bucket_name', models.CharField(blank=True, default='', max_length=255)),
                ('s3_region', models.CharField(blank=True, default='', max_length=50)),
                ('cloudinary_cloud_name', models.CharField(blank=True, default='', max_length=255)),
                ('cloudinary_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('cloudinary_api_secret', apps.configuration.fields.EncryptedTextField(blank=True, default='')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_success', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Storage Configuration',
            },
        ),
    ]