# Generated by Django 6.0.7 on 2026-08-30 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0005_part5_requirements_updated_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('ADVANCE_PAYMENT', 'Advance Payment'), ('FINAL_PAYMENT', 'Final Payment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Rupees, not paise — see money.py.', max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ORDER_CREATED', 'Order Created'), ('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('VERIFICATION_FAILED', 'Verification Failed')], db_index=True, default='CREATED', max_length=25)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, default='', max_length=50)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
                ('customer', models.ForeignKey(help_text="Denormalized from booking.customer at creation time for direct querying (a customer's full payment history shouldn't require joining through every booking) — booking.customer remains the source of truth.", limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ORDER_CREATED', 'Payment order created'), ('VERIFICATION_ATTEMPTED', 'Payment verification attempted'), ('VERIFIED', 'Payment verified'), ('VERIFICATION_FAILED', 'Payment verification failed'), ('CAPTURED', 'Payment captured'), ('FAILED', 'Payment failed'), ('WEBHOOK_RECEIVED', 'Webhook received'), ('WEBHOOK_VERIFICATION_FAILED', 'Webhook verification failed'), ('REFUND_INITIATED', 'Refund initiated'), ('REFUND_PROCESSED', 'Refund processed'), ('RECONCILIATION_MISMATCH', 'Reconciliation mismatch'), ('RECONCILIATION_OK', 'Reconciliation confirmed')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null for system/webhook-triggered events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_order_id', models.CharField(max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paise', models.PositiveBigIntegerField(help_text='What was actually sent to Razorpay — see money.py.')),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('receipt', models.CharField(help_text="Razorpay's receipt field — max 40 chars.", max_length=40, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ATTEMPTED', 'Attempted'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='CREATED', max_length=15)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_payment_id', models.CharField(max_length=64, unique=True)),
                ('razorpay_signature', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], db_index=True, max_length=20)),
                ('method', models.CharField(blank=True, default='', help_text='card / upi / netbanking / wallet — from Razorpay, not entered.', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.paymentorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('snapshotted_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='price_snapshot', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_refund_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='INITIATED', max_length=15)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.paymenttransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_event_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('signature_verified', models.BooleanField(default=False)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='payments_we_event_t_8f0131_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', '-created_at'], name='payments_pa_custome_a935a8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking', 'phase'], name='payments_pa_booking_9bee43_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('booking', 'phase'), name='unique_payment_per_booking_phase'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['payment', '-created_at'], name='payments_pa_payment_a3a0f0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['payment', '-created_at'], name='payments_pa_payment_0c6878_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment_order', '-created_at'], name='payments_pa_payment_796a0c_idx'),
        ),
    ]